### PR TITLE
Add instructions for auto/latest-anchore-tools branch

### PR DESCRIPTION
**Pull request by DaneWeber**
See the first auto-generated PR: https://github.com/anchore/anchore-engine/pull/1191

There have been several commits to the `auto/latest-anchore-tools` branch which have been overridden by the GitHub Action force-pushing to it.

This PR adds clarifying text to the PR auto-generated by the GitHub Action.

### CODE REVIEW

**Review by Vijay-P — APPROVED** [review]
LGTM. How does it work if the code needs to be updated again before the branch/PR is created. Will it automagically make a new PR?

**Review by nightfurys — APPROVED** [review]
lgtm

**Comment by DaneWeber** [comment]
> LGTM. How does it work if the code needs to be updated again before the branch/PR is created. Will it automagically make a new PR?

See https://github.com/marketplace/actions/create-pull-request#action-behaviour for the action's approach to creating PRs only when there is a relevant diff.

The GitHub action we have defined will always start on the latest `master`, check for newer releases of Syft & Grype, and create a PR if so.

Is that what you're looking for, @Vijay-P ? I might not be following your question.

**Comment by DaneWeber** [comment]
I'm merging based on the approvals. If @Vijay-P 's questions lead to something that needs to be adjusted or clarified, we can open a new PR.

**Pull request merged**
