### PR TITLE
Update Skopeo and use list-tags

### PR DESCRIPTION
**Pull request by anxolerd**
This PR updates Skopeo version in the docker image and utilizes `skopeo list-tags` command to retrieve tags from remote repository. This fixes issues with adding repositories which does not contain `latest` tag to anchore-engine.

References: 
- #236
- #484

### CODE REVIEW

**Comment by zhill** [comment]
Hi @anxolerd ! First, thanks for the work on this. It's something we've had on the to-do list for a while. We'll review!

**Comment by zhill** [comment]
With this update, it's also possible to remove: https://github.com/anchore/anchore-engine/blob/master/anchore_engine/services/apiext/swagger/swagger.yaml#L1164 since that API parameter is used for handling the old behavior of skopeo.

**Comment by anxolerd** [comment]
@zhill , I've deleted some should-be outdated and no more required references to lookuptag in 06ab80c.

**Comment by zhill** [comment]
Thanks for the update @anxolerd ! Will do some testing and review and update here. This is much appreciated work. Thanks!

**Review by zhill — APPROVED** [review]
lgtm

**Review by dakaneye — APPROVED** [review]
This looks good to me! Thanks @anxolerd !

It's cool that we don't need a lookup tag anymore as well, which is confusing when you're trying to add a whole "repo"

@zhill I think it'd be really useful to have some integration tests for the skopeo_wrapper just so we can have a bit more confidence around changes here, but I tested these locally and verified the skopeo command (on v1.2.1) works well and should output the correct format used here

**Comment by zhill** [comment]
Thanks @anxolerd and @dakaneye !

**Pull request merged**
