### PR TITLE
Bump to UBI 8.4

### PR DESCRIPTION
**Pull request by robertp**

### CODE REVIEW

**Review by nightfurys — COMMENTED** [review]
lgtm. Just curious if there's been an ask to bump the ubi tag? And does it introduce any dependency updates as well?

**Comment by nightfurys** [comment]
Other upstream repositories might also need a similar update

**Review by zhill — COMMENTED** [review]
lgtm

**Comment by robertp** [comment]
> lgtm. Just curious if there's been an ask to bump the ubi tag? And does it introduce any dependency updates as well?



> lgtm. Just curious if there's been an ask to bump the ubi tag? And does it introduce any dependency updates as well?

@nightfurys IronBank is mandating UBI 8.4 now so it seems reasonable to bump our version rather than hand-crafting a release w/different upstreams for them.

**Pull request merged**
