### PR TITLE
fix error message, add field_name parameter to improve error message usefulness

### PR DESCRIPTION
**Pull request by dakaneye**
Signed-off-by: Samuel Dacanay <sam.dacanay@anchore.com>

**What this PR does / why we need it**: Resolves an issue with error messages around failure to convert a date time string into a date time object

**Which issue this PR fixes** *(optional, in `fixes #<issue number>)(, fixes #<issue_number, ...)` format, will close the issue when PR is merged*: Fixes https://github.com/anchore/anchore-engine/issues/787

**Special notes**:

### CODE REVIEW

**Review by dspalmer99 — APPROVED** [review]
LGTM, pending rebase on master.

**Comment by zhill** [comment]
Presumably the "date-time" spec in the swagger spec for the API isn't RFC3339 specific, but we can replace that with a specific regex in the API spec for that field and it will handle the validation at the API layer just like other types of checks and it should return a decent error message in that case. Would that approach suffice or was it tried and did not sufficiently indicate the problem?

**Comment by dakaneye** [comment]
> Presumably the "date-time" spec in the swagger spec for the API isn't RFC3339 specific, but we can replace that with a specific regex in the API spec for that field and it will handle the validation at the API layer just like other types of checks and it should return a decent error message in that case. Would that approach suffice or was it tried and did not sufficiently indicate the problem?

@zhill I didn't consider adding it to the API spec, that's an interesting idea. I pulled this thread and started building/searching for a pre-existing regex for RFC3339 date time strings and there's a few long and complex regexes we could use:

```
"^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\.\\d+)?[A-Z]?(?:[+.-](?:08:\\d{2}|\\d{2}[A-Z]))?$"
```

Presumably, we'd want to match each of the 3 formats we support internally:
```python
rfc3339_date_input_fmts = [
    "%Y-%m-%dT%H:%M:%SZ",
    "%Y-%m-%dT%H:%M:%S.%fZ",
    "%Y-%m-%dT%H:%M:%S:%fZ",
]
```

Should I go ahead and pursue this path? I'm sure it would have value later on for date-time fields.

**Comment by zhill** [comment]
> > Presumably the "date-time" spec in the swagger spec for the API isn't RFC3339 specific, but we can replace that with a specific regex in the API spec for that field and it will handle the validation at the API layer just like other types of checks and it should return a decent error message in that case. Would that approach suffice or was it tried and did not sufficiently indicate the problem?
> 
> @zhill I didn't consider adding it to the API spec, that's an interesting idea. I pulled this thread and started building/searching for a pre-existing regex for RFC3339 date time strings and there's a few long and complex regexes we could use:
> 
> ```
> "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\.\\d+)?[A-Z]?(?:[+.-](?:08:\\d{2}|\\d{2}[A-Z]))?$"
> ```
> 
> Presumably, we'd want to match each of the 3 formats we support internally:
> 
> ```python
> rfc3339_date_input_fmts = [
>     "%Y-%m-%dT%H:%M:%SZ",
>     "%Y-%m-%dT%H:%M:%S.%fZ",
>     "%Y-%m-%dT%H:%M:%S:%fZ",
> ]
> ```
> 
> Should I go ahead and pursue this path? I'm sure it would have value later on for date-time fields.

Yes, let's give that a try since it has less code impact as well as having consistent error responses for input format validation.

**Comment by dakaneye** [comment]
@zhill seems to work! I tested the regex against the 3 formats and it works for those so we should be good!

**Review by zhill — APPROVED** [review]
lgtm. I'd like to review making this consistent across the API using a common type definition here (e.g. "rfc3339"), but works for this fix.

**Pull request merged**
