### PR TITLE
Updated docker-compose.yaml

### PR DESCRIPTION
**Pull request by roachmd**
What this PR does / why we need it:

1) This PR is to update the docker-compose.yaml file to match the directions given in the comments section of the yaml.
2) Added a line in the description on where to copy the anchore-prometheus.yaml file from and to.
3) Rename anchore-prometheus.yml to anchore-prometheus.yaml to be consistent with naming

### CODE REVIEW

**Comment by nurmi** [comment]
thanks for the PR @roachmd!  We’ll take a look and respond here to track progress.

**Comment by nurmi** [comment]
Hi @roachmd - thanks again for the PR!

We've done a review and have a couple of asks before merging:

1) we'll need you to sign off on the commit in order to merge your contribution - you can review our contributor doc (with instructions using git) here - https://github.com/anchore/anchore-engine/blob/master/CONTRIBUTING.rst

2) I noticed there are some changes in the docker-compose.yaml that are not related to the prometheus renaming (uncommented PG exposed ports, removal of the :Z on volume mounts) - can you remove those changes so that the PR is just about the prometheus file rename?

Best Regards,
-Dan

**Comment by roachmd** [comment]
Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: roachmd <roach.d.michael@gmail.com>

**Comment by nurmi** [comment]
thank you @roachmd !

**Pull request merged**
