### PR TITLE
Add support for assuming AWS Roles

### PR DESCRIPTION
**Pull request by sonaltr**
Anchore (If hosted on AWS EC2) currently assumes the role provided to it (if the config is set to `awsauto`) This is great to provide the EC2 instance access to the account's ECR. However, if you wanted to have cross account ECR access, this does not work.

After a talk with @nurmi and @zhill , this pull request addresses that issue. It uses the `_iam_role` as the key on the request to assume the role (sent as the secret) and pull the required image.

### CODE REVIEW

**Comment by zhill** [comment]
Thanks @sonaltr ! I'll give it a review and some testing and if things look good we'll merge it. Before we merge it, you need to sign the contributor agreement at https://github.com/anchore/anchore-engine/blob/master/CONTRIBUTING.rst. You can do that by amending the commit using '-s' for a sign-off line or manually adding it to the commit message.

**Comment by sonaltr** [comment]
@zhill just updated the commit message. Please let me know if there are any other issues/concerns.

**Comment by zhill** [comment]
Test went well. Merged. UX-wise it can be challenging to not see the arn in the cli's 'registry list' or 'registry get' output, but handling viewing credentials is a general issue we need to tackle and not specific to this PR. Thanks @sonaltr!

**Comment by naman** [comment]
Hey @zhill. The current implementation of sts.assume_role in anchore doesn't support cross-account ECR access with accounts that require an external_id to be passed (in order to assume the role). Please review the following PR https://github.com/anchore/anchore-engine/pull/225 (If all goes well, I understand the documentation will need to be updated accordingly).

**Comment by zhill** [comment]
@naman ack, will review and comment in #225

**Pull request merged**
