### PR TITLE
passlib 1.7.4 version bump address a couple bugs.

### PR DESCRIPTION
**Pull request by Toure**
**What this PR does / why we need it**:
There are a couple corrections/improvement to the CrypContext class which is used in anchore-engine for password
hasher for database accounts.

* CryptContext will now throw UnknownHashError when it can’t identify a hash provided to methods such as CryptContext.verify(). Previously it would throw a generic ValueError.

**Which issue this PR fixes**
closes: #855 

**Special notes**:

### CODE REVIEW

**Comment by nightfurys** [comment]
@Toure, is this PR still active? Looks like the pyyaml commit may be included in https://github.com/anchore/anchore-engine/pull/864 already?

**Comment by zhill** [comment]
We still need this update for passlib itself

**Comment by Toure** [comment]
> We still need this update for passlib itself
Yes just waiting on a review.

**Review by zhill — APPROVED** [review]
lgtm

**Pull request merged**
