### PR TITLE
Global max images

### LINKED ISSUE #700: Add archive rule for total image count
Add ability to set per-account or system global archive rule to archive all but the N newest images in the system.

This facilitates simpler control of the total db size usage deployment size without deleting images but rather archiving them when they fall outside boundary for the N-newest.

### PR DESCRIPTION
**Pull request by dakaneye**
**What this PR does / why we need it**: Fixes #700 

**Which issue this PR fixes** *(optional, in `fixes #<issue number>)(, fixes #<issue_number, ...)` format, will close the issue when PR is merged*: fixes #:

**Special notes**:

### CODE REVIEW

**Comment by zhill** [comment]
Will do a closer review, but looks like you're missing the upgrade code for the additional db column added.

**Comment by dakaneye** [comment]
> Will do a closer review, but looks like you're missing the upgrade code for the additional db column added.

@zhill You're right, added now

**Comment by dakaneye** [comment]
This needs another change to expose the new fields to the API, and found some problems with the actual rule processing, gonna push another commit

**Comment by dakaneye** [comment]
Merging with verbal permission from @zhill

**Pull request merged**
