### PR TITLE
Parameterize CI for python version/tox env

### PR DESCRIPTION
**Pull request by robertp**

### CODE REVIEW

**Review by zhill — APPROVED** [review]
lgtm

**Comment by zhill** [comment]
@robertp I'm ok to merge this, but do you mind if I squash merge it to keep the commit history a bit cleaner? I think the commits can be lumped into one logically consistent commit, but if not let me know and I'll just merge w/o a squash.

**Comment by robertp** [comment]
> @robertp I'm ok to merge this, but do you mind if I squash merge it to keep the commit history a bit cleaner? I think the commits can be lumped into one logically consistent commit, but if not let me know and I'll just merge w/o a squash.

@zhill Absolutely, I'll squash merge!

**Comment by alfredodeza** [comment]
This is great @robertp ! Is this py36/py38 meant for the transition only? Or do we plan to keep both? Parametrizing in this way paves the way to check 3.9 which is great.

**Pull request merged**
