### PR TITLE
More efficient response chunk handling in internal HTTP client

### LINKED ISSUE #1010: Improve performance of http.py for large download transfers
The chunking logic in https://github.com/anchore/anchore-engine/blob/master/anchore_engine/clients/services/http.py can cause performance issues when lots of chunks are used and thus memory is re-allocated a lot for single transfers.

The reason for chunking on downloads is to minimize the buffer sizes needed in request-library functions that are cached and cause overall memory consumption since the are thread-local. Thus, a solution must balance performance with memory consumption for large (100MB+) transfers.

Code to test options and evaluate:
```
#!/usr/bin/env python3                                                                                                                                                                                                           
import requests
import json
import time
import sys
import io
import psutil
import os
import resource
import subprocess
def fget_req_stringio(url, **kwargs):
    httpcode = 500
    jsondata = {}
    chunk_size = int(1024.0 * 1000.0 * 1)
    try:
        r = requests.get(url, stream=True, **kwargs)
        httpcode = r.status_code
        with io.StringIO() as iobuf:
            for rchunk in r.iter_content(chunk_size):
                iobuf.write(str(rchunk, 'utf-8'))
            rawdata = iobuf.getvalue()
        try:
            jsondata = json.loads(rawdata)
        except:
            jsondata = {}
    except Exception as err:
        rawdata = str(err)
        print(err)
    return httpcode, jsondata, rawdata
def fget_req(url, **kwargs):
    httpcode = 500
    rawdata = b''
    jsondata = {}
    chunk_size = int(1024.0 * 1000.0 * 1)
    try:
        r = requests.get(url, stream=True, **kwargs)
        httpcode = r.status_code
        with io.BytesIO() as iobuf:
            for rchunk in r.iter_content(chunk_size):
                iobuf.write(rchunk)
            rawdata = iobuf.getvalue()
        try:
            jsondata = json.loads(str(rawdata, 'utf-8'))
        except:
            jsondata = {}
    except Exception as err:
        rawdata = str(err)
        print(err)
    return httpcode, jsondata, rawdata
def fget_req_orig(url, **kwargs):
    httpcode = 500
    rawdata = b''
    jsondata = {}
    chunk_size = int(1024.0 * 1000.0 * 1)
    try:
        r = requests.get(url, stream=True, **kwargs)
        httpcode = r.status_code
        for rchunk in r.iter_content(chunk_size):
            rawdata = rawdata + rchunk
        try:
            jsondata = json.loads(str(rawdata, 'utf-8'))
        except:
            jsondata = {}
    except Exception as err:
        rawdata = str(err)
        print(err)
    return httpcode, jsondata, rawdata
url = "http://repos.lax.layerhost.com/centos/8-stream/isos/x86_64/CentOS-Stream-8-x86_64-20210503-boot.iso"
url = "http://localhost:1234/index.html"
testfile = 'littlejson'
fs_location = "/bigdisk/nginx_content/{}".format(testfile)
test_output = "/tmp/{}".format(testfile)
url = "http://localhost/{}".format(testfile)
test_outputs = []
dosio = dobio = doorig = False
try:
    if sys.argv[1] == 'sio':
        dosio = True
    elif sys.argv[1] == 'bio':
        dobio = True
    elif sys.argv[1] == 'orig':
        doorig = True
    else:
        raise Exception("noopt")
except Exception as err:
    print ("USAGE: {} <sio|bio|orig>".format(sys.argv[0]))
    sys.exit(1)
if dosio:
    timer = time.time()
    c, j, b  = fget_req_stringio(url)
    print ("TOT_TIME STRINGIO: {}".format(time.time() - timer))
    print (j.keys())
    test_output_sio = "{}.sio".format(test_output)
    test_outputs.append(test_output_sio)
    with open(test_output_sio, 'w') as OFH:
        OFH.write(b)
if dobio:
    timer = time.time()    
    c, j, b  = fget_req(url)
    print ("TOT_TIME IOBUF: {}".format(time.time() - timer))
    print (j.keys())
    test_output_bio = "{}.bio".format(test_output)
    test_outputs.append(test_output_bio)    
    with open(test_output_bio, 'wb') as OFH:
        OFH.write(b)
if doorig:
    timer = time.time()
    c, j, b  = fget_req_orig(url)
    print ("TOT_TIME ORIG: {}".format(time.time() - timer))
    print (j.keys())
    test_output_orig = "{}.orig".format(test_output)
    test_outputs.append(test_output_orig)        
    with open(test_output_orig, 'wb') as OFH:
        OFH.write(b)
#process = psutil.Process(os.getpid())
#print(process.memory_info().rss / 1000)
test_output_locations = ' '.join(test_outputs)
cmd = 'md5sum {} {}'.format("{}".format(test_output_locations), fs_location)
sout = subprocess.check_output(cmd.split())
for line in str(sout, 'utf-8').splitlines():
    print(line)
print ("MAX MEM (RSS) USED: {} KB".format(resource.getrusage(resource.RUSAGE_SELF).ru_maxrss))
sys.exit(0)
```

### PR DESCRIPTION
**Pull request by zhill**
Fixes #1010 . No functional change, just better peformance.

### CODE REVIEW

**Review by dakaneye — APPROVED** [review]
looks good ! Might be nice to throw the chunking in a unit test, but we can open up a follow up if need be.

**Comment by zhill** [comment]
> looks good ! Might be nice to throw the chunking in a unit test, but we can open up a follow up if need be.

Yes, agree this whole module needs a revisit w/tests and some cleanup.

**Comment by mathrock** [comment]
@zhill @dakaneye  I believe this is only a partial fix.  While you fixed the `fget_req` method there are still others using the previous chunking logic (see below).  Of note, the put/post methods are used by `anchy_{put,post}` for various catalog, policy-engine and simplequeue requests.

- [fpost_req](https://github.com/anchore/anchore-engine/blob/master/anchore_engine/clients/services/http.py#L60-L69)
- [fput_req](https://github.com/anchore/anchore-engine/blob/master/anchore_engine/clients/services/http.py#L113-L122)
- [fdelete_req](https://github.com/anchore/anchore-engine/blob/master/anchore_engine/clients/services/http.py#L225-L234)

Thanks

**Comment by zhill** [comment]
You are correct @mathrock . Those can be updated, but they are not impacting the system behavior as much due to the payloads for those responses being much smaller. POST, PUT, and DELETE operations do not have the payload size problems that GET does. We'll review those as part of a more comprehensive update to this module. The chunking fix only impacts the response streaming, not the upload path itself (for POST and PUT). I'll update the title of this issue to reflect the specific scope and open another to track the wider updates in this module.

**Pull request merged**
