### PR TITLE
get the latest evaluation result from database if the newest_only is …

### PR DESCRIPTION
**Pull request by armstrongli**
…true

**What this PR does / why we need it**:
Fix one issue on kubernetes webhook

**Which issue this PR fixes** *(optional, in `fixes #<issue number>)(, fixes #<issue_number, ...)` format, will close the issue when PR is merged*: fixes #:

* https://github.com/anchore/anchore-engine/issues/81

**Special notes**:

The logic change part is to check the existing evaluation result first, then do evaluation if there're no evaluation records in the database.

### CODE REVIEW

**Comment by zhill** [comment]
@armstrongli Thanks for digging in and submitting this PR, we definitely appreciate the work and contribution, and we'll definitely work to solve the performance issue with you.

However, in this PR it looks like you're significantly changing the semantics of the 'newest_only' flag in the internal catalog API from it's original intent and in ways that have impacts to other parts of the API. The original intent was to control the number of results returned, not short-circuit the evaluation. I understand the desire to achieve that short-circuit, but implementing it there has implications on the rest of the system and the overall accuracy of the policy evaluation results.

Specifically, with the proposed change, any user call to 'anchore-cli evaluate check ' would only return the first policy evaluation ever done unless a user also has the policy_evaluation subscription active for the tag, and then only for the newest image mapped to that tag, so untagged images would never have their policy evaluations updated to reflect new CVEs, policy changes, or other external updates that impact the policy result.

There is definitely a bug in the 'newest_only' handling, and a fix for that will reduce some db traffic, but this PR is making a significant semantic change to how the engine behaves, so as-is I can't accept it, but I am happy to merge a PR for fixing the newest_only bug that does not change the semantics of the call:

Fix the invocation to pass the param -- https://github.com/anchore/anchore-engine/blob/master/anchore_engine/services/catalog/api/controllers/policy_evaluations.py#L31

Fix the lookup (add a 'limit 1' on the query itself in the db_policyeval.tsget_byfilter via a new parameter like 'limit=None' in function declaration) -- https://github.com/anchore/anchore-engine/blob/master/anchore_engine/services/catalog/api/controllers/policy_evaluations.py#L165

I definitely want to help fix your core issue: slow k8s webhook performance. Probably accomplished by introducing a proper cache with things like ttl control in the handler or as an external client, and I'm happy to follow up on this with you if you're interested in tackling it or helping. I'm going to be working on something here in the next few days to add support for Validating and Mutating webhooks from k8s as well.

**Comment by armstrongli** [comment]
@zhill 
Agree with you that this PR is changing the meaning of the `newest_only` flag. The flag should be a flag to change the set of  queries from anchore eval list. 

>  Probably accomplished by introducing a proper cache with things like ttl control in the handler or as an external client,

I think it's not the best option to set up a external cache for the evaluation result as the cache has no idea what is happening in the backend, and don't know when to refresh the cache. By anchore engine, the valuation result will never change if 
1. there're no CVE changes
2. there're no image updates
3. there're no policy updates

And anchore engine itself has the full context on the image and know when to re-evaluate the image and when to refresh the result in the table. 
There're subscriptions set up in anchore engine - vuln_update, analysis_update, tag_update, etc. - and it is available for anchore engine to detect which images should be re-evaluate and when to update the result. 
A cache server is an extremely thin layer without any context on the backend service. and it is better to have a fast sync between cache layer and service layer.

**Comment by zhill** [comment]
@armstrongli fundamentally, your description of the update condition is correct (except that any feed update can cause a policy eval change, not just CVEs), but that is not currently implemented in the system and those existing subscriptions only cover the currently tagged image, which is not the same scope as the policy evaluation code, which can evaluate any image based on digest whether currently tagged or not. What you're describing is definitely what we'll get to, but only at that point is it safe for the rest of the system to change the semantics of the _newest_only_ parameter. Before those other changes are made this change can lead to very stale evaluations that may never get updated in some cases.

The most direct solution to your issue, performance in the webhook, can be accomplished with a very simple cache that just remembers the (image digest, tag, bundle id, result) tuple for say 30 or 60 seconds and reduces hits to the policy engine. That should get you over the performance issue while we work to implement the more sophisticated update logic you described, which is certainly the better long-term solution and has been in our plans for a while.

I've also run into this with other webhook handlers (ValidatingWebhooks for anchore in other projects), so I'll prioritize the full state check work for the next release and will keep #82 updated. Once that is in place the newest_only flag shouldn't be necessary as the api call for getting a policy evaluation should work as efficiently as possible in any invocation. If you're interested in contributing this work that would be great and we can discuss where/how it should work (check for feed sync since last eval, bundle update, if any has changed, re-run the evaluation, else return the last eval).

If you want to fix the newest_only bug as I described in my initial response, or file a new PR to implement the design you and I discussed around checking image, policy, and feed sync state, I'm happy to review those as well.

**Comment by zhill** [comment]
This should be no longer an issue with the interactive evaluation and changes in 0.3.1 of anchore-engine to support policy evalutions only when either the image, feeds, or policy has changed. See: eec019d6533e3bc7e51ddd91993094e0c4be127e (there are a couple of follow-up bug fixes, but that commit is the primary feature).

**Pull request closed without merging**
